In [1]:
import pandas as pd
import numpy as np

In [2]:
import matplotlib.pyplot as plt

In [3]:
dataset=pd.read_csv(r"C:\Users\DIGITAL\Desktop\finaldataset.csv",encoding="ISO-8859-1")
dataset

C:\Users\DIGITAL\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3020: DtypeWarning: Columns (13,14,15) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


dateCrawled  seller offerType       dateCreated  postalCode  \
0       24-03-2016 11:52  privat   Angebot  24-03-2016 00:00     70435.0   
1       24-03-2016 10:58  privat   Angebot  24-03-2016 00:00     66954.0   
2       14-03-2016 12:52  privat   Angebot  14-03-2016 00:00     90480.0   
3       17-03-2016 16:54  privat   Angebot  17-03-2016 00:00     91074.0   
4       31-03-2016 17:25  privat   Angebot  31-03-2016 00:00     60437.0   
5       04-04-2016 17:36  privat   Angebot  04-04-2016 00:00     33775.0   
6       01-04-2016 20:48  privat   Angebot  01-04-2016 00:00     67112.0   
7       21-03-2016 18:54  privat   Angebot  21-03-2016 00:00     19348.0   
8       04-04-2016 23:42  privat   Angebot  04-04-2016 00:00     94505.0   
9       17-03-2016 10:53  privat   Angebot  17-03-2016 00:00     27472.0   
10      26-03-2016 19:54  privat   Angebot  26-03-2016 00:00     96224.0   
11      07-04-2016 10:06  privat   Angebot  07-04-2016 00:00     57290.0   
12      15-03-2016 22:49  privat   Angebot  15-03-2016 00:00     37269.0   
13      21-03-2016 21:37  privat   Angebot  21-03-2016 00:00     90762.0   
14      21-03-2016 12:57  privat   Angebot  21-03-2016 00:00      4177.0   
15      11-03-2016 21:39  privat   Angebot  11-03-2016 00:00     24148.0   
16      01-04-2016 12:46  privat   Angebot  01-04-2016 00:00     38871.0   
17      20-03-2016 10:25  privat   Angebot  20-03-2016 00:00     65599.0   
18      23-03-2016 15:48  privat   Angebot  23-03-2016 00:00     88361.0   
19      01-04-2016 22:55  privat   Angebot  01-04-2016 00:00     49565.0   
20      01-04-2016 19:56  privat   Angebot  01-04-2016 00:00     75365.0   
21      27-03-2016 11:38  privat   Angebot  27-03-2016 00:00     68309.0   
22      23-03-2016 14:52  privat   Angebot  23-03-2016 00:00     49716.0   
23      12-03-2016 19:43  privat   Angebot  12-03-2016 00:00      9526.0   
24      13-03-2016 20:40  privat   Angebot  13-03-2016 00:00     35390.0   
25      18-03-2016 21:44  privat   Angebot  18-03-2016 00:00     73765.0   
26      10-03-2016 19:38  privat   Angebot  10-03-2016 00:00     31139.0   
27      07-03-2016 12:51  privat   Angebot  07-03-2016 00:00     12621.0   
28      09-03-2016 11:56  privat   Angebot  09-03-2016 00:00     87471.0   
29      08-03-2016 19:55  privat   Angebot  08-03-2016 00:00     86199.0   
...                  ...     ...       ...               ...         ...   
371511  11-03-2016 15:50  privat   Angebot  11-03-2016 00:00     65936.0   
371512  08-03-2016 13:52  privat   Angebot  08-03-2016 00:00     24850.0   
371513  21-03-2016 23:40  privat   Angebot  21-03-2016 00:00     38470.0   
371514  26-03-2016 18:36  privat   Angebot  26-03-2016 00:00     34320.0   
371515  01-04-2016 12:59  privat   Angebot  01-04-2016 00:00     34414.0   
371516  01-04-2016 01:55  privat   Angebot  31-03-2016 00:00     90439.0   
371517  07-03-2016 17:06  privat   Angebot  07-03-2016 00:00     61169.0   
371518  03-04-2016 19:56  privat   Angebot  03-04-2016 00:00     58730.0   
371519  20-03-2016 18:47  privat   Angebot  20-03-2016 00:00      1217.0   
371520  16-03-2016 17:06  privat   Angebot  16-03-2016 00:00     56472.0   
371521  02-04-2016 16:43  privat   Angebot  02-04-2016 00:00     23820.0   
371522  11-03-2016 23:40  privat   Angebot  11-03-2016 00:00     87700.0   
371523  06-03-2016 21:11  privat   Angebot  05-03-2016 00:00     60437.0   
371524  31-03-2016 18:50  privat   Angebot  31-03-2016 00:00      4275.0   
371525  25-03-2016 18:48  privat   Angebot  25-03-2016 00:00     90473.0   
371526  21-03-2016 15:36  privat   Angebot  21-03-2016 00:00     45896.0   
371527  04-04-2016 11:45  privat   Angebot  04-04-2016 00:00     88477.0   
371528  09-03-2016 11:36  privat   Angebot  09-03-2016 00:00     18246.0   
371529  04-04-2016 09:57  privat   Angebot  04-04-2016 00:00     48653.0   
371530  28-03-2016 13:48  privat   Angebot  28-03-2016 00:00     75223.0   
371531  02-04-2016 20:37  privat   Angebot  02-04-2016 00:00 

In [4]:
dataset.isnull().any()

dateCrawled            True
seller                 True
offerType              True
dateCreated            True
postalCode             True
model                  True
lastSeen               True
nrOfPictures           True
name                   True
vehicleType            True
abtest                 True
carage                 True
gearbox                True
powerPS                True
kilometer              True
monthOfRegistration    True
fuelType               True
brand                  True
notRepairedDamage      True
price                  True
dtype: bool

In [5]:
km1=dataset.iloc[:,5]

In [6]:
dataset["vehicleType"].mode()


0    limousine
dtype: object

In [7]:
dataset["vehicleType"].isnull().any()

True

In [8]:
dataset.isnull().any()

dateCrawled            True
seller                 True
offerType              True
dateCreated            True
postalCode             True
model                  True
lastSeen               True
nrOfPictures           True
name                   True
vehicleType            True
abtest                 True
carage                 True
gearbox                True
powerPS                True
kilometer              True
monthOfRegistration    True
fuelType               True
brand                  True
notRepairedDamage      True
price                  True
dtype: bool

In [9]:
dataset.dropna(inplace=True)

In [10]:
dataset.isnull().any()

dateCrawled            False
seller                 False
offerType              False
dateCreated            False
postalCode             False
model                  False
lastSeen               False
nrOfPictures           False
name                   False
vehicleType            False
abtest                 False
carage                 False
gearbox                False
powerPS                False
kilometer              False
monthOfRegistration    False
fuelType               False
brand                  False
notRepairedDamage      False
price                  False
dtype: bool

In [11]:
dataset

dateCrawled  seller offerType       dateCreated  postalCode  \
3       17-03-2016 16:54  privat   Angebot  17-03-2016 00:00     91074.0   
4       31-03-2016 17:25  privat   Angebot  31-03-2016 00:00     60437.0   
5       04-04-2016 17:36  privat   Angebot  04-04-2016 00:00     33775.0   
6       01-04-2016 20:48  privat   Angebot  01-04-2016 00:00     67112.0   
7       21-03-2016 18:54  privat   Angebot  21-03-2016 00:00     19348.0   
10      26-03-2016 19:54  privat   Angebot  26-03-2016 00:00     96224.0   
11      07-04-2016 10:06  privat   Angebot  07-04-2016 00:00     57290.0   
14      21-03-2016 12:57  privat   Angebot  21-03-2016 00:00      4177.0   
17      20-03-2016 10:25  privat   Angebot  20-03-2016 00:00     65599.0   
18      23-03-2016 15:48  privat   Angebot  23-03-2016 00:00     88361.0   
19      01-04-2016 22:55  privat   Angebot  01-04-2016 00:00     49565.0   
20      01-04-2016 19:56  privat   Angebot  01-04-2016 00:00     75365.0   
21      27-03-2016 11:38  privat   Angebot  27-03-2016 00:00     68309.0   
23      12-03-2016 19:43  privat   Angebot  12-03-2016 00:00      9526.0   
24      13-03-2016 20:40  privat   Angebot  13-03-2016 00:00     35390.0   
25      18-03-2016 21:44  privat   Angebot  18-03-2016 00:00     73765.0   
27      07-03-2016 12:51  privat   Angebot  07-03-2016 00:00     12621.0   
28      09-03-2016 11:56  privat   Angebot  09-03-2016 00:00     87471.0   
29      08-03-2016 19:55  privat   Angebot  08-03-2016 00:00     86199.0   
30      03-04-2016 15:48  privat   Angebot  03-04-2016 00:00     53879.0   
33      25-03-2016 21:48  privat   Angebot  25-03-2016 00:00     39179.0   
34      17-03-2016 18:55  privat   Angebot  17-03-2016 00:00     67071.0   
38      01-04-2016 17:45  privat   Angebot  01-04-2016 00:00     10551.0   
39      25-03-2016 15:50  privat   Angebot  25-03-2016 00:00     22767.0   
43      13-03-2016 15:47  privat   Angebot  13-03-2016 00:00     59174.0   
45      29-03-2016 18:57  privat   Angebot  29-03-2016 00:00     84180.0   
46      15-03-2016 18:59  privat   Angebot  15-03-2016 00:00     53604.0   
47      04-04-2016 00:38  privat   Angebot  03-04-2016 00:00     86157.0   
49      04-04-2016 14:06  privat   Angebot  04-04-2016 00:00     35576.0   
55      26-03-2016 10:39  privat   Angebot  26-03-2016 00:00     56759.0   
...                  ...     ...       ...               ...         ...   
371492  13-03-2016 12:51  privat   Angebot  13-03-2016 00:00     49536.0   
371493  26-03-2016 23:25  privat   Angebot  26-03-2016 00:00     63065.0   
371494  12-03-2016 16:48  privat   Angebot  12-03-2016 00:00     21147.0   
371496  07-03-2016 09:54  privat   Angebot  07-03-2016 00:00     77694.0   
371500  14-03-2016 16:52  privat   Angebot  14-03-2016 00:00     86609.0   
371501  15-03-2016 01:51  privat   Angebot  14-03-2016 00:00     72766.0   
371502  13-03-2016 15:45  privat   Angebot  13-03-2016 00:00     30519.0   
371503  22-03-2016 10:37  privat   Angebot  22-03-2016 00:00     91301.0   
371504  15-03-2016 20:25  privat   Angebot  15-03-2016 00:00     60439.0   
371505  04-04-2016 14:41  privat   Angebot  04-04-2016 00:00     17509.0   
371510  05-03-2016 15:54  privat   Angebot  05-03-2016 00:00     88213.0   
371512  08-03-2016 13:52  privat   Angebot  08-03-2016 00:00     24850.0   
371513  21-03-2016 23:40  privat   Angebot  21-03-2016 00:00     38470.0   
371514  26-03-2016 18:36  privat   Angebot  26-03-2016 00:00     34320.0   
371515  01-04-2016 12:59  privat   Angebot  01-04-2016 00:00     34414.0   
371516  01-04-2016 01:55  privat   Angebot  31-03-2016 00:00     90439.0   
371518  03-04-2016 19:56  privat   Angebot  03-04-2016 00:00     58730.0   
371519  20-03-2016 18:47  privat   Angebot  20-03-2016 00:00      1217.0   
371521  02-04-2016 16:43  privat   Angebot  02-04-2016 00:00     23820.0   
371523  06-03-2016 21:11  privat   Angebot  05-03-2016 00:00     60437.0   
371524  31-03-2016 18:50  privat   Angebot  31-03-2016 00:00 

In [12]:
km2=dataset.iloc[:,5]

In [13]:
x=dataset.iloc[:,9:19].values

In [14]:
x

array([['kleinwagen', 'test', 18.0, ..., 'benzin', 'volkswagen', 'nein'],
       ['kleinwagen', 'test', 11.0, ..., 'diesel', 'skoda', 'nein'],
       ['limousine', 'test', 24.0, ..., 'benzin', 'bmw', 'ja'],
       ...,
       ['bus', 'control', 19.0, ..., 'benzin', 'opel', 'nein'],
       ['cabrio', 'test', 19.0, ..., 'benzin', 'smart', 'nein'],
       ['bus', 'test', 23.0, ..., 'diesel', 'volkswagen', 'nein']],
      dtype=object)

In [15]:
x.shape

(260964, 10)

In [16]:
y=dataset.iloc[:,19:20].values
y

array([[1500.],
       [3600.],
       [ 650.],
       ...,
       [1150.],
       [1199.],
       [9200.]])

In [17]:
y.shape

(260964, 1)

In [18]:
from sklearn.preprocessing import LabelEncoder

In [19]:
le=LabelEncoder()
le1=LabelEncoder()
le2=LabelEncoder()
le3=LabelEncoder()
le4=LabelEncoder()
le5=LabelEncoder()



In [20]:
x

array([['kleinwagen', 'test', 18.0, ..., 'benzin', 'volkswagen', 'nein'],
       ['kleinwagen', 'test', 11.0, ..., 'diesel', 'skoda', 'nein'],
       ['limousine', 'test', 24.0, ..., 'benzin', 'bmw', 'ja'],
       ...,
       ['bus', 'control', 19.0, ..., 'benzin', 'opel', 'nein'],
       ['cabrio', 'test', 19.0, ..., 'benzin', 'smart', 'nein'],
       ['bus', 'test', 23.0, ..., 'diesel', 'volkswagen', 'nein']],
      dtype=object)

In [21]:
x[:,0]=le.fit_transform(x[:,0])

In [22]:
x[:,1]=le.fit_transform(x[:,1])

In [23]:
x[:,3]=le.fit_transform(x[:,3])

In [24]:
x[:,7]=le.fit_transform(x[:,7])

In [25]:
x[:,8]=le.fit_transform(x[:,8])

In [26]:
x[:,9]=le.fit_transform(x[:,9])

In [27]:
x

array([[4, 1, 18.0, ..., 1, 37, 1],
       [4, 1, 11.0, ..., 3, 31, 1],
       [6, 1, 24.0, ..., 1, 2, 0],
       ...,
       [1, 0, 19.0, ..., 1, 24, 1],
       [2, 1, 19.0, ..., 1, 32, 1],
       [1, 1, 23.0, ..., 3, 37, 1]], dtype=object)

In [28]:
#after label encoding
x.shape

(260964, 10)

In [29]:
from sklearn.preprocessing import OneHotEncoder

In [30]:
oh=OneHotEncoder()
oh1=OneHotEncoder()
oh2=OneHotEncoder()

In [31]:
oh=OneHotEncoder(categorical_features=[0])
x=oh.fit_transform(x).toarray()

C:\Users\DIGITAL\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\DIGITAL\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:390: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [32]:
#after onehotencoding of vehicle type column 
x.shape

(260964, 17)

In [33]:
#removing dummy column
x=x[:,1:]

In [34]:
#after removing dummy column 
x.shape

(260964, 16)

In [35]:
oh1=OneHotEncoder(categorical_features=[13])
x=oh1.fit_transform(x).toarray()

C:\Users\DIGITAL\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\DIGITAL\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:390: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [36]:
#after onehotencoding of fuel type column 
x.shape

(260964, 22)

In [37]:
#removing dummy column
x=x[:,1:]

In [38]:
#after removing dummy column
x.shape

(260964, 21)

In [39]:
oh2=OneHotEncoder(categorical_features=[19])
x=oh2.fit_transform(x).toarray()

C:\Users\DIGITAL\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\DIGITAL\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:390: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [40]:
#after onehotencoding of brand column 
x.shape

(260964, 59)

In [41]:
#removing dummy column
x=x[:,1:]

In [42]:
#after removing dummy column
x.shape

(260964, 58)

In [43]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test =train_test_split(x,y,test_size=0.2,random_state=0)

In [44]:
#from sklearn.preprocessing import StandardScaler

In [45]:
#sc=StandardScaler()

In [46]:
#x_train=sc.fit_transform(x_train)
#x_test=sc.transform(x_test)

In [47]:
import keras

Using TensorFlow backend.


In [48]:
from keras.models import Sequential
from keras.layers import Dense

In [49]:
model=Sequential()

In [50]:
model.add(Dense(input_dim=58,init="random_uniform",output_dim=18,activation="relu"))

C:\Users\DIGITAL\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(input_dim=58, activation="relu", units=18, kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


Instructions for updating:
Colocations handled automatically by placer.


In [51]:
model.add(Dense(init="random_uniform",output_dim=13))

C:\Users\DIGITAL\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=13, kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


In [52]:
model.add(Dense(init="random_uniform",output_dim=3))

C:\Users\DIGITAL\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=3, kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


In [53]:
model.add(Dense(init="random_uniform",output_dim=1))

C:\Users\DIGITAL\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=1, kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


In [54]:
model.compile(optimizer='adam',loss='mean_squared_error',metrics=['mse'])

In [55]:
model.fit(x_train,y_train,epochs=50,batch_size=8)

Instructions for updating:
Use tf.cast instead.
Epoch 1/50
208771/208771 [==============================] - 33s 159us/step - loss: 146728704977.1607 - mean_squared_error: 146728704977.1607
Epoch 2/50
208771/208771 [==============================] - 31s 149us/step - loss: 146724360466.2675 - mean_squared_error: 146724360466.2675
Epoch 3/50
208771/208771 [==============================] - 31s 151us/step - loss: 146730085503.6777 - mean_squared_error: 146730085503.6777
Epoch 4/50
208771/208771 [==============================] - 32s 153us/step - loss: 146718516909.0047 - mean_squared_error: 146718516909.0047
Epoch 5/50
208771/208771 [==============================] - 32s 152us/step - loss: 146714580778.8762 - mean_squared_error: 146714580778.8762
Epoch 6/50
208771/208771 [==============================] - 30s 141us/step - loss: 146711137795.1864 - mean_squared_error: 146711137795.1864
Epoch 7/50
208771/208771 [==============================] - 32s 151us/step - loss: 146712507745.8680 - mea

In [56]:
model.save("project_class.h5")

In [57]:
y_train.shape

(208771, 1)

In [58]:
y_pred=model.predict(x_test)


In [59]:
y_pred

array([[2686.7742],
       [5894.458 ],
       [4214.327 ],
       ...,
       [2593.105 ],
       [5121.241 ],
       [6998.3687]], dtype=float32)

In [60]:
y_test

array([[1295.],
       [3100.],
       [1800.],
       ...,
       [1750.],
       [2200.],
       [5150.]])

In [61]:
y_pred

array([[2686.7742],
       [5894.458 ],
       [4214.327 ],
       ...,
       [2593.105 ],
       [5121.241 ],
       [6998.3687]], dtype=float32)

In [62]:
y_pred[9]

array([4454.5474], dtype=float32)

In [63]:
y_test[9]

array([2199.])

In [64]:
y_pred[12]

array([5076.5576], dtype=float32)

In [65]:
y_test[12]

array([1599.])

In [66]:
y_pred[200]

array([4396.471], dtype=float32)

In [67]:
y_test[200]

array([5800.])

In [68]:
y_pred[6]

array([9047.25], dtype=float32)

In [69]:
y_test[6]

array([5000.])

In [70]:
y_test[14]

array([1500.])

In [71]:
y_pred[14]

array([6836.4253], dtype=float32)

In [72]:
from sklearn.metrics import r2_score

In [73]:
r2_score(y_test,y_pred)*100

0.8236211875398247

In [74]:
from sklearn.metrics import mean_squared_error

In [75]:
mean_squared_error(y_test,y_pred)

2461929111.825511

In [76]:
model.save("project_class.h5")